# Site settings
title: Cat Dad On A Mission
header-img: img/home-bg.png
email: maskiella@gmail.com
copyright_name: saurookadook
description: > # this means to ignore newlines until "baseurl:"
  Cats, code, music, games, politics, and whatever else I can think of
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  saurookadook
learn_profile: saurookadook
email_username: maskiella@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
